name: CI Workflow Advance (Training + Docker)

# Trigger: Jalan setiap ada push ke branch main
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Environment Variables Global (Koneksi ke DagsHub)
env:
  MLFLOW_TRACKING_URI: "https://dagshub.com/anggazakariiya/Eksperimen_SML_Angga_Zakariya.mlflow"
  MLFLOW_TRACKING_USERNAME: "anggazakariiya"
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
  DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
  REPO_NAME: "Eksperimen_SML_Angga_Zakariya"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Set up job & Checkout Code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Python 3.12
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # 3. Check Environment
    - name: Check Env
      run: |
        python --version
        ls -R

    # 4. Install Dependencies
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install mlflow==2.19.0 dagshub scikit-learn pandas numpy matplotlib seaborn joblib virtualenv

    # 5. Run MLflow Project (Training Model)
    - name: Run MLflow Project
      run: |
        cd MLProject
        mlflow run . --env-manager=local --experiment-name "Eksperimen_Diabetes_Advance"

    # 6. Get latest MLflow run_id (SCRIPT PENTING)
    - name: Get latest MLflow run_id
      id: get_run
      run: |
        run_id=$(python -c "import mlflow; runs = mlflow.search_runs(experiment_names=['Eksperimen_Diabetes_Advance'], order_by=['start_time DESC'], max_results=1); print(runs.iloc[0].run_id)")
        echo "Latest Run ID: $run_id"
        echo "run_id=$run_id" >> $GITHUB_OUTPUT

    # 7. Upload to GitHub Artifacts (Pengganti Google Drive)
    - name: Upload Model to GitHub Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: model-diabetes-pkl
        path: MLProject/model_diabetes.pkl

    # 8. Build Docker Model (Syarat Advance)
    - name: Build Docker Image from Model
      run: |
        mlflow models build-docker \
          -m "runs:/${{ steps.get_run.outputs.run_id }}/model_rf_tuned" \
          -n "${{ secrets.DOCKER_USERNAME }}/diabetes-model:latest" \
          --enable-mlserver

    # 9. Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 10. Push Docker Image
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/diabetes-model:latest
